### ISSUE TITLE
Timer on each question for admins/ count of participants

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-vote#445] opened 2022-12-01 12:19 UTC
**User Story**
As an admin. , I want to get a better overview about how far we come with a vote on one question so that the voting on one question can be closed

**Acceptance Criteria**
1. Timer on question as soon as the question is published Estimate:
2. Count of particpants - show how many of the acitve participants have voted Estimate:

**Comment by amelienbawolski** [comment] 2022-12-01 12:19
@StevenMalaihollo @JakubC-projects can you estimate the time on each of the accaptance criteria?

**Comment by StevenMalaihollo** [comment] 2023-06-01 07:48
Duplicate of https://github.com/bcc-code/bcc-vote/issues/453

**Closed by StevenMalaihollo** 2023-06-01 07:48 UTC
Labels: 220 Vote
